version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: "host"
    command: "uvicorn --host 0.0.0.0 api.app:app"
    env_file:
      - .env
    ports:
    - "8000:8000"
